### ISSUE TITLE
apiserver address guessing can fail

### ISSUE THREAD

**Issue by awoimbee** [allegroai/clearml-web#47]
https://github.com/allegroai/clearml-web/blob/9efcccf621167b4c30657cefa525af4ea75eb96e/src/app/app.constants.ts#L96

### My use-case:
I have a wildcard TLS certificate, it works for `*.mydomain.xyz` but not for `*.*.mydomain.xyz`, so to avoid provisioning a special TLS cert to have `app.clearml.mydomain.xyz`, I used `clearml-app.mydomain.xyz` (and `clearml-api.mydomain.xyz`).

### The issue:
The config that "create credentials" prints is wrong.

#### Why:
The code I linked above doesn't find the `https?:\/\/(demo|)app\.` pattern so the webapp thinks my apiserver is at `clearml-app.mydomain.xyz:8008` (which is false).
This issue is only cosmetic, the webapp works great.

### Possible solution:
The clearml-webserver container already does quite a bit of substitutions and it already knows the apiserver address. It could inform webserver.
A not so bad way of doing that is for the entrypoint script to `sed` variables before starting nginx ([like that](https://moreillon.medium.com/environment-variables-for-containerized-vue-js-applications-f0aa943cb962)).

**Comment by shyallegro** [comment]
Hi @awoimbee ,
please note the code on https://github.com/allegroai/clearml-web/blob/9efcccf621167b4c30657cefa525af4ea75eb96e/src/app/app.constants.ts#L120
by default the system expects a reverse proxy on `/api` as defined in `environment.prod.ts` during build or  `configuration.json` on start, if you build a special version you can update the configuration or mount another configuration.json file into docker to suite your special needs.

**Comment by awoimbee** [comment]
Thanks !
I'l try and close the issue if successful, then I'll probably open a PR on the helm chart.

**Comment by antonaleks** [comment]
Hi, all!
I am facing a similar problem because I am using domain  kind `app-xxx-xxx-xxx-xxx-xxx.mydomain.xyz` where `xxx` ip address. 

The problem is that on the frontend when forming `clearml.conf` the api server address is output exactly the same as the web server. This happens because my address does not get into the regexp pattern https?:\/\/(demo|)app\. as there is a `-` sign after app and not `.`

To solve this problem I see two ways 
- to add `-` sign to the pattern `https?:\/\/(demo|)app[\-\.]` 
- to pass the url through environment variables, but in this case will change the proxy server configuration

Do you know, maybe there are alternative options? My infrastructure is deployed to k8s, maybe i should set env API_BASE_URL in my pod of clearml web server to `api-xxx-xxx-xxx-xxx-xxx.mydomain.xyz`?

**Comment by shyallegro** [comment]
Hi @antonaleks,
if you only need to override the URL we display as a configuration hint you can use this key 
`displayedServerUrls?: {apiServer?: string; filesServer?: string};`
add it to your `configuration.json` file and mount it to the root folder of clearml  webapp in `/usr/share/nginx/html/`

**Comment by antonaleks** [comment]
> Hi @antonaleks, if you only need to override the URL we display as a configuration hint you can use this key `displayedServerUrls?: {apiServer?: string; filesServer?: string};` add it to your `configuration.json` file and mount it to the root folder of clearml webapp in `/usr/share/nginx/html/`

If i use helm chart to deploy clearml, should i put this config to values.yaml like
```
webserver:
  additionalConfigs:
          apiServer: "https://api-${local.record_name}"
          filesServer: "https://files-${local.record_name}"
```

I tryed this way, but in my web server pod there are no /usr/share/nginx/html/configuration.json after helm upgrade. But configmap was deployed to k8s.

**Comment by valeriano-manassero** [comment]
Helm chart addresses these configurations in this way:
```
clearml:
  clientConfigurationApiUrl: "https://<my domain>"
  clientConfigurationFilesUrl: "https://<my domain>"
```

you can find reference in README in chart folders: https://github.com/allegroai/clearml-helm-charts/tree/main/charts/clearml

**Comment by graelo** [comment]
Hi, I have the same question if I don't use helm but simply the docker container:

When I mount the following content at `/usr/share/nginx/html/configuration.json`, the web browser still points at the guessed `apiBaseUrl` (port 8008) which is incorrect in my case:

```json
{
  "apiBaseUrl": "http://192.x.x.x:9022",
  "displayedServerUrls": {
    "apiServer": "http://192.x.x.x:9022",
    "filesServer": "http://192.x.x.x:9023"
  }
}
```

I'd like to know what I am missing: is it a wrong syntax, a missing trigger to have the ts code read that file, or something else?

Thanks!

PS: I've read https://github.com/allegroai/clearml-web/blob/master/src/app/app.constants.ts and https://github.com/allegroai/clearml-web/blob/master/src/environments/base.ts, it looks to me that the syntax and nesting is correct.

**Comment by graelo** [comment]
I noticed that this line https://github.com/allegroai/clearml-web/blob/29c68abeb4533d5b4a3232896b8fd81f16fa5503/src/app/webapp-common/clearml-applications/report-widgets/src/main.ts#L17 has been commented out, preventing the `configuration.json` to be loaded (IIUC).

Is there an alternative mechanism?

**Comment by shyallegro** [comment]
Hi @graelo, this code is only relevant to report widgets and not the main webapp as widgets don't use the configuration service.
webapp still make this call in `src/main.ts`

**Comment by alexpusch** [comment]
@shyallegro 
I have the same issue as the original issue describes.
I have managed to set configuration.json by adding this to the webserver helm values:

```
webserver:
  additionalConfigs: 
      configuration.json: "{\"apiBaseUrl\":\"https://...domain.com\"}"
```

This did the expected and now the configuration.json HTTP request done at clearml start returns the needed apiBaseUrl.

Despite this, clearml still outputs requests to the wrong guessed URL. Specifically  https://...domain.com:8008/v2.24/login.supported_modes 

From my investigation this is due to the `updateHttpUrlBaseConstant()` method in app.constanst.ts run before configuration.json fetching.

login.service.ts get the api path using - `protected basePath = HTTP.API_BASE_URL;` which is not up to date with configuration.json values

Can you advice? I'm really don't want to build a custom image for this

**Comment by shyallegro** [comment]
Hi @alexpusch 
we have an option to configure ngnix reverse proxy with environment variables, I initially thought it was only for docker, so didn't point you this way.
passing these variables should point nginx reverse proxy at the right servers `NGINX_APISERVER_ADDRES` and/or `NGINX_FILESERVER_ADDR`
by default without specifying `configuration.json` the UI will point to nginx `/api` and `/files` reverse proxy locations.

**Comment by alexpusch** [comment]
@shyallegro thanks for the answer.
Where should I pass these variables to? We use Helm chart to deploy clearml, should I pass the vars as extra variables to the webserver or apiserver? 

Currently the UI requests this url `https://...domain.com:8008/v2.24` and not `https://...domain.com/api`

**Comment by shyallegro** [comment]
@alexpusch to the web server instance
we had a bug in 1.10.0 image which didn't set the api path to `/api`, please make sure you are using 1.10.1 to get the fix.

**Comment by jkhenning** [comment]
@alexpusch these should go to the webserver deployment

**Comment by alexpusch** [comment]
@shyallegro @jkhenning Upgrading to 1.10.1 solved the issue. Did not had to change Nginx env vars. Thanks for the help 👍
